config/routes.rb
Rails.application.routes.draw do
  root 'areas#index'
  resources :comments
  resources :listings
  resources :users
  resources :listing_categories
  resources :areas, only: [:index, :show]
  resources :login, only: [:new, :create]

  delete 'logout', to: 'login#destroy', as: 'log_out'
  delete 'comment', to: 'comments#destroy', as: 'delete_comment'
  delete 'listing', to: 'listings#destroy', as: 'delete_listing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :listing_category
  has_many :comments
  has_many :users, through: :comments

  validates :title, :price, presence: true
  validates :description, length: { in: 10..400 }
  validates :price, length: { in: 1..255}

  def area_name
      self.listing_category.area.name
  end

  def listing_area
    self.listing_category.area
  end

  def cat_name
    self.listing_category.name
  end 
  
  def listing_post_date
    #"#{self.created_at.strftime('%b')} #{self.created_at.day} #{self.created_at.time}"
    "#{self.created_at.strftime("%B %d, %Y at %l:%M")}"
  end

  def order_comments
    self.comments.all.order.created_at
  end

  def user_comments
    self.order_comments.each do |comment|
      puts comment.content
    end
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

    skip_before_action :save_my_previous_url, only: [:new, :edit, :create, :update]
    skip_before_action :fetch_user, only: [:index, :show]

    def index
        @listings = Listing.all
    end

    def show
        @listing = Listing.find(params[:id])
        @comments = @listing.comments
        @comment = Comment.new
        if logged_in?
            @user = User.find(session[:user_id])
        end
    end

    def new
        @new_listing = Listing.new
    end

    def create
        @listing = Listing.create(listing_params)
        if @listing.valid?
            redirect_to @listing
        else
            flash[:errors] = @listing.errors.full_messages
            redirect_to new_listing_path
        end
    end

    def edit
        # if session[:user_id] == @listing.user.id
        #     redirect_to edit_listing_path(@listing)
        # else
        #     redirect_to new_login_path
        # end  
        @listing = Listing.find(params[:id])  
    end

    def update
        @listing = Listing.find(params[:id])  
        @listing.update(listing_params)
        if @listing.valid?
            redirect_to @listing
        else
            flash[:errors] = @listing.errors.full_messages
            redirect_to edit_listing_path(@listing)
        end
    end

    def destroy
        @listing = Listing.find(params[:format])
        @category = @listing.listing_category
        @listing.destroy
        redirect_to @category
    end

    private

    def listing_params
        params.require(:listing).permit( :title, :description, :price, :user_id, :listing_category_id)
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.erb
<div class= "page">
<%= form_for @listing do |f|%>
    <%= f.label :title%>
    <%= f.text_field :title%><br>
    <%= f.label :description%>
    <%= f.text_area :description%><br>
    <%= f.label :price%>
    <%= f.text_field :price%><br>
    <%= f.collection_select :listing_category_id, ListingCategory.all, :id, :name %><br>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit%>
<%end %>
</div>

app/views/listings/edit.erb
<div class="page">
<%= form_for @listing do |f|%>
    <%= f.label :title%>
    <%= f.text_field :title%><br>
    <%= f.label :description%>
    <%= f.text_area :description%><br>
    <%= f.label :price%>
    <%= f.text_field :price%><br>
    <%= f.collection_select :listing_category_id, ListingCategory.all, :id, :name %><br>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit%>
<%end %>

<%= button_to "Delete listing", delete_listing_path(@listing), method: :delete %>

<% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
        <p style="color:red" > <%= error %> </p>
    <% end %>
<% end %>

</div>

app/views/listings/new.erb
<div class="page">
<%= form_for @new_listing do |f|%>
    <%= f.label :title%>
    <%= f.text_field :title%><br>
    <%= f.label :description%>
    <%= f.text_area :description%><br>
    <%= f.label :price%>
    <%= f.text_field :price%><br>
    <%= f.collection_select :listing_category_id, @user.user_area_cats , :id, :name %><br>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit%>
<%end %>


<% if flash[:errors] %>
    <% flash[:errors].each do |error|%>
    <p style="color:red" > <%= error %> </p>
    <% end %>
<% end %>
<div>

app/views/listings/show.erb
<div class="page">
<h1><%= @listing.title %></h1><br>
<h3>Posted By: <%= link_to @listing.user.name, user_path(@listing.user) %></h3><br>
<p>Description: <%= @listing.description.tr('[]', '').tr('""', '') %></p>
<p>Category:<%= @listing.listing_category.name %></p>
<p>Price/Pay Rate: <%= @listing.price %></p><br>
<p>Posted on: <%= @listing.listing_post_date %></p><br>

<%if session[:user_id] == @listing.user_id %>
<p class= "small"><%= link_to "Edit post", edit_listing_path(@listing) %></p>  
<%end%>

<% if session[:user_id] == @listing.user_id %>
<p class= "small"><%= link_to "Remove Listing", delete_listing_path(@listing), method: :delete %></p>
<% end %>

<ul>
<% @comments.each do |comment| %>
        <li>
        <p class= "small"><%= link_to comment.user.name, user_path(comment.user)%><%=" said on #{comment.comment_post_date}"%></p>
        <p><%= comment.content %> </p>
        <%if session[:user_id] == comment.user.id %>
    <p class="small"><%= link_to "Edit Comment", edit_comment_path(comment) %></p>
        </li>
        <% end %>
    <%end%>
</ul>


<h3> Create a new comment? </h3>
<% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
        <p style="color:red" > <%= error %> </p>
    <% end %>
<% end %>



<%if logged_in? %>
<% @user = User.find(session[:user_id]) %>
<div class= "box"><%= form_for @comment do |f| %><br>
<%= f.text_area :content %><br>
    <%= f.hidden_field :listing_id, value: @listing.id %>
    <%= f.hidden_field :user_id, value: @user.id %>
    <%= f.submit %>
<% end %> </div>
<% else %>
    <p>Log In to Make a Comment</p>
<% end %>
</div>