config/routes.rb
Rails.application.routes.draw do
  root 'areas#index'
  resources :comments
  resources :listings
  resources :users
  resources :listing_categories
  resources :areas, only: [:index, :show]
  resources :login, only: [:new, :create]

  delete 'logout', to: 'login#destroy', as: 'log_out'
  delete 'comment', to: 'comments#destroy', as: 'delete_comment'
  delete 'listing', to: 'listings#destroy', as: 'delete_listing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :listing

  validates :content, length: { in: 2..200 }

  def listing_path
    self.listing.id
  end

  def comment_post_date
    "#{self.created_at.strftime("%B %d, %Y at %l:%M")}"
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :get_comment, only: [:show, :edit, :update]
    skip_before_action :fetch_user, only: [:show]
    skip_before_action :save_my_previous_url

    def show
    end

    def new
        @comment = Comment.new
    end

    def create
        @comment = Comment.create(comment_params)
        if @comment.valid?
            redirect_to @comment.listing
        else
            flash[:errors] = @comment.errors.full_messages
            redirect_to listing_path(@comment.listing)
        end
    end

    def edit

    end

    def update
        @comment.update(comment_params)
        if @comment.valid?
            redirect_to listing_path(@comment.listing_path)
        else
            flash[:errors] = @comment.errors.full_messages
            redirect_to edit_comment_path(@comment)
        end
    end

    def destroy
        @comment = Comment.find(params[:format])
        @comment.destroy
        redirect_to session[:my_previous_url]
    end

    private

    def comment_params
        params.require(:comment).permit(:content, :user_id, :listing_id)
    end

    def get_comment
        @comment = Comment.find(params[:id])
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/edit.html.erb
<div class="page">
<%= form_for @comment do |f| %>
    <p class= "small"><%= f.label :content %></p>
    <%= f.text_area :content %><br>
    <%= f.hidden_field :listing_id, value: @comment.listing.id %>
    <%= f.submit %>
<% end %> 
<%= button_to "Delete Comment", delete_comment_path(@comment), method: :delete %>
<% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
        <p style="color:red" > <%= error %> </p>
    <% end %>
<% end %>
</div>

app/views/comments/new.html.erb
<div class= "page">
<%= form_for @comment do |f| %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.hidden_field :listing_id, value: @comment.listing.id %>
    <%= f.submit %>
<% end %>

<% if flash[:errors] %>
        <% flash[:errors].each do |error|%>
        <p style="color:red" > <%= error %> </p>
    <% end %>
<% end %>

<br> <%= link_to "Home. Temp button", areas_path %>
</div>

app/views/comments/show.html.erb
<div class= "page">
<h1><%= @comment.user.name %> says:</h1><br>
<p><%= @comment.content %></p><br>

<%= link_to "Delete Comment", destroy_comment_path %>
</div>