config/routes.rb
Rails.application.routes.draw do
  root 'areas#index'
  resources :comments
  resources :listings
  resources :users
  resources :listing_categories
  resources :areas, only: [:index, :show]
  resources :login, only: [:new, :create]

  delete 'logout', to: 'login#destroy', as: 'log_out'
  delete 'comment', to: 'comments#destroy', as: 'delete_comment'
  delete 'listing', to: 'listings#destroy', as: 'delete_listing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/area.rb
class Area < ApplicationRecord
    has_many :users
    has_many :listing_categories
    has_many :listings, through: :listing_categories

    validates :name, presence: true
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController

    skip_before_action :fetch_user

    def index
        session[:page] = "/index"
        @areas = Area.all
    end

    def show
        @area = Area.find(params[:id])
    end

end

app/helpers/areas_helper.rb
module AreasHelper
end

app/views/areas/index.html.erb
<div class= "page">
<h1>Welcome to DavisList</h1><br>
<h2>Please Select An Area</h2>
<ul>
<p><% @areas.each do |area| %>
    <li>
    <%= link_to area.name, area_path(area) %><br>
    </li>
<% end %>
</ul>
</div>

app/views/areas/show.erb
<div class="page">
<h3 class="region"> Region: <%= @area.name %></h3>
<h4 class="zip_code"> Zip Code: <%= @area.zip_code %></h4>
 <p> Categories: <% @area.listing_categories.each do |listing_category| %>
    <li class="categories">
    <%= link_to listing_category.name, listing_category %> <p class= "small"> Listings: <%= listing_category.listing_amount %>
    </li>
<%end%>
</div>