config/routes.rb
Rails.application.routes.draw do
  root 'areas#index'
  resources :comments
  resources :listings
  resources :users
  resources :listing_categories
  resources :areas, only: [:index, :show]
  resources :login, only: [:new, :create]

  delete 'logout', to: 'login#destroy', as: 'log_out'
  delete 'comment', to: 'comments#destroy', as: 'delete_comment'
  delete 'listing', to: 'listings#destroy', as: 'delete_listing'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DavisList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <header>
  <div class="navbar">
    <h1 class="davis_list">DavisList
    <%if @listing != nil%>
      <p class= "small"><%= link_to @listing.area_name, @listing.listing_area%> > <%= link_to @listing.cat_name, @listing.listing_category%> > <%= @listing.title%></p>
    <% elsif @listing_category != nil%>
      <p class= "small"><%= link_to @listing_category.area_name, @listing_category.area %> > <%= @listing_category.name %></p>
    <% elsif @new_listing != nil%>
    <p class= "small"> <%= link_to @user.area.name,  @user.area %> > New Listing </p> 
    <%elsif @area != nil %>
    <p class= "small"> <%= @area.name %></p> 
    <% end %>
    </h1>

  <div class= "status_bar"><% if logged_in? %>
    Logged in as: <button class="logged_in"><%= link_to User.find_by(id: session[:user_id]).name, user_path(session[:user_id]) %></button>
    <button id="log_out"><%= link_to "Log out", log_out_path, method: :delete %></button>
    <button class= "nlisting"><%= link_to "Make a New Listing", new_listing_path%></button>
  <%else%>
  <button class="sign_up"><%= link_to "Sign up", new_user_path %></button>
  <button class="log_in"><%= link_to "Log in", new_login_path %></button>
 
  <%end%>
  <button class="home"> <%= link_to "Homepage", areas_path %> </button>
  </div>
</div>


  </header>

  <body>

    <%= yield %>

  </body>
</html>